name: toggle_search
description: A new Flutter project.

publish_to: 'none' 

version: 0.1.0

environment:
  sdk: '>=2.18.0-5.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_rotation: ^2.0.0
  font_awesome_flutter: ^10.1.0
  google_fonts: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
